import 'bootstrap';
import 'ymaps';
import 'skycons';
import '@fortawesome/fontawesome-free/js/fontawesome';
import '@fortawesome/fontawesome-free/js/solid';
import './assets/scss/all_styles.scss';
import './app/data';
import './app/init';
import './app/createForm';
